"""empty message

Revision ID: 00980ff767c2
Revises: 5078509efb33
Create Date: 2022-03-06 18:15:40.344097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00980ff767c2'
down_revision = '5078509efb33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'password')
    # ### end Alembic commands ###
